# Image for base ruby environment
MAINTAINER kyle-cook

# Using alpine base
FROM alpine:latest

# Give ourselves a non-root user
USER ruby

# Copy all the gems into the image
#ADD ./gems ~/.ruby/gems
